[theme]
# Forzar el tema claro corporativo
base = "light"

# Color principal para botones y resaltados (Rojo corporativo)
primaryColor = "#d9232e"

# Color de fondo principal
backgroundColor = "#ffffff"

# Color de fondo secundario (para el panel lateral)
secondaryBackgroundColor = "#f4f6f9"

# Color del texto (Gris oscuro para máxima legibilidad)
textColor = "#262730"

# Tipo de fuente
font = "sans serif"
